@extends('student.main')

@section('head-scripts')
    {{--We can add scripts for header here--}}
    <link href="{{ asset('plugins/calendar/dist/fullcalendar.css') }}" rel="stylesheet">
@endsection

@section('title')
    Timetable
@endsection

@section('breadcrumbs')
    <div class="row page-titles">
        <div class="col-md-5 col-8 align-self-center">
            <h3 class="text-themecolor m-b-0 m-t-0">Timetable</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active">Timetable</li>
            </ol>
        </div>
    </div>
@endsection

@section('page-content')
    {{--Content goes here--}}
    {{-- Selector for the timetable --}}
    <div class="row hidden-xs-only">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">
                        Select for custom results
                    </h4>
                    {{-- Selectors for the month --}}
                    <div class="row">
                        <div class="col-sm-3">
                            <select name="" id="" class="form-control">
                                <option value="">-- Select Month --</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <select name="" id="" class="form-control">
                                <option value="">-- Select Acad Year --</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <select name="" id="" class="form-control">
                                <option value="">-- Select Faculty --</option>
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <select name="" id="" class="form-control">
                                <option value="">-- Select Room --</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- Here comes the real time table --}}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <h4 class="title">Student Timetable</h4>
                    <div id="calendar">
                        {{-- Generated by cal-init.js --}}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('bottom-scripts')
    {{--Scripts before the end of body tag go here--}}
    <script src="{{ asset('plugins/calendar/jquery-ui.min.js') }}"></script>
    <script src="{{ asset('plugins/moment/moment.js') }}"></script>
    <script src="{{ asset('plugins/calendar/dist/fullcalendar.min.js') }}"></script>
    <script src="{{ asset('plugins/calendar/dist/cal-init.js') }}"></script>
@endsection